version: '3'
services:
  nginx:
    image: nginx:latest
    container_name: "nginx"
    ports:
      - "8080:80"
    volumes:
      - ${APP_CODE_PATH_HOST}:/app
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /app

  node:
    image: node:lts-alpine
    container_name: node
    tty: true
    working_dir: ${APP_CODE_PATH_CONTAINER}
    volumes:
      - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}
